name: Ostival Desktop

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    timeout-minutes: 120

    env:
      CMAKE_GENERATOR: Ninja

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Qt
        uses: jurplel/install-qt-action@v4
        with:
          version: '6.10.*'
          cache: true

      - name: Install Qt Dependencies (Linux only)
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y libgl1-mesa-dev '^libxcb.*-dev' libxkbcommon-x11-dev libgstreamer1.0-dev libgstreamer-plugins-base1.0-dev

      - name: Set up MSVC (Windows only)
        if: runner.os == 'Windows'
        uses: ilammy/msvc-dev-cmd@v1

      - name: Configure project
        run: cmake -S . -B build -DCMAKE_BUILD_TYPE=Release

      - name: Build project
        run: cmake --build build --config Release --parallel

      - name: Run tests
        run: |
          if [ -f "build/CTestTestfile.cmake" ]; then
            ctest --test-dir build --output-on-failure
          else
            echo "No tests found. Skipping."
          fi
        shell: bash